# Generated by Django 3.2.3 on 2021-05-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('mail', models.CharField(max_length=200)),
                ('psw', models.CharField(max_length=10)),
                ('pswr', models.CharField(max_length=10)),
            ],
        ),
    ]
